spring:

  #  DB, JWT 관련 정보  (gitIgnore)
  config:
    import:
      - secret/datasource.yml
      - secret/jwt.yml
      - secret/printer.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    time-zone: Asia/Seoul

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 10
